2016-07-02 13:24:47 ERROR [pool-3-thread-1] org.apache.log4j.Logger.error(Logger.java:261) - 获取Redis中的值时出现异常：redis.clients.jedis.exceptions.JedisDataException: ERR no such key
ExceptionStackTrace: ---------------start------------------------
	redis.clients.jedis.Protocol.processError(Protocol.java:117)
	redis.clients.jedis.Protocol.process(Protocol.java:151)
	redis.clients.jedis.Protocol.read(Protocol.java:205)
	redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:196)
	redis.clients.jedis.Jedis.lset(Jedis.java:957)
	org.bi.redis.RedisManage.modList(RedisManage.java:805)
	org.bi.manage.app.thread.APPMessageThread.heartbeat(APPMessageThread.java:182)
	org.bi.manage.app.thread.APPMessageThread.run(APPMessageThread.java:58)
	org.bi.manage.app.dispatch.APPMonitor.MessageCallback(APPMonitor.java:251)
	org.bi.kafka.server.KafkaServerFixThread.run(KafkaServerFixThread.java:57)
	java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	java.util.concurrent.FutureTask.run(FutureTask.java:138)
	java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	java.lang.Thread.run(Thread.java:662)
ExceptionStackTrace: ---------------end------------------------

